### ISSUE TITLE
Is it possible to be able to use it add a pre-commit hook?

### ISSUE THREAD

**Issue by sbrunner** [mheap/json-schema-spell-checker#121]
As I understand, we jest need to add a config file named `.pre-commit-hooks.yaml`.
https://pre-commit.com/#creating-new-hooks

With something like:
```
- id: json-schema-spell-checker 
  name: json-schema-spell-checker 
  entry: json-schema-spell-checker 
  language: node
```

And add some documentation.

See also pre-commit usage: https://pre-commit.com/#usage

If you are interested, I can provide a pull request :-)

**Comment by mheap** [comment]
@sbrunner Yes please!
