### ISSUE TITLE
~ is unrecognised

### ISSUE THREAD

**Issue by savage-alex** [mheap/json-schema-spell-checker#7]
When retrieving the path names via `$paths[*]~` the wave symbol is unrecognised and causes the parser to error:

node:11892) UnhandledPromiseRejectionWarning: Error: Lexical error on line 1. Unrecognized text.
$..tags[*]~
----------^
    at Parser.parseError

**Comment by mheap** [comment]
I've just released version 2.0.0 which resolves this
